package main

var dot, dash, lSpace, wSpace = "\u2022", "\u2013", "\u0020", "\u0020\u0020"
var eToItuMap = map[string]string{
	"a":  dot + dash + lSpace,
	"b":  dash + dot + dot + dot + lSpace,
	"c":  dash + dot + dash + dot + lSpace,
	"d":  dash + dot + dot + lSpace,
	"e":  dot + lSpace,
	"f":  dot + dot + dash + dot + lSpace,
	"g":  dash + dash + dot + lSpace,
	"h":  dot + dot + dot + dot + lSpace,
	"i":  dot + dot + lSpace,
	"j":  dot + dash + dash + dash + lSpace,
	"k":  dash + dot + dash + lSpace,
	"l":  dot + dash + dot + dot + lSpace,
	"m":  dash + dash + lSpace,
	"n":  dash + dot + lSpace,
	"o":  dash + dash + dash + lSpace,
	"p":  dot + dash + dash + dot + lSpace,
	"q":  dash + dash + dot + dash + lSpace,
	"r":  dot + dash + dot + lSpace,
	"s":  dot + dot + dot + lSpace,
	"t":  dash + lSpace,
	"u":  dot + dot + dash + lSpace,
	"v":  dot + dot + dot + dash + lSpace,
	"w":  dot + dash + dash + lSpace,
	"x":  dash + dot + dot + dash + lSpace,
	"y":  dash + dot + dash + dash + lSpace,
	"z":  dash + dash + dot + dot + lSpace,
	"0":  dash + dash + dash + dash + dash + lSpace,
	"1":  dot + dash + dash + dash + dash + lSpace,
	"2":  dot + dot + dash + dash + dash + lSpace,
	"3":  dot + dot + dot + dash + dash + lSpace,
	"4":  dot + dot + dot + dot + dash + lSpace,
	"5":  dot + dot + dot + dot + dot + lSpace,
	"6":  dash + dot + dot + dot + dot + lSpace,
	"7":  dash + dash + dot + dot + dot + lSpace,
	"8":  dash + dash + dash + dot + dot + lSpace,
	"9":  dash + dash + dash + dash + dot + lSpace,
	".":  dot + dash + dot + dash + dot + dash + lSpace,
	",":  dash + dash + dot + dot + dash + dash + lSpace,
	"?":  dot + dot + dash + dash + dot + dot + lSpace,
	"'":  dot + dash + dash + dash + dash + dot + lSpace,
	"!":  dash + dot + dash + dot + dash + dash + lSpace,
	"/":  dash + dot + dot + dash + dot + lSpace,
	"(":  dash + dot + dash + dash + dot + lSpace,
	")":  dash + dot + dash + dash + dot + dash + lSpace,
	"&":  dot + dash + dot + dot + dot + lSpace,
	":":  dash + dash + dash + dot + dot + dot + lSpace,
	";":  dash + dot + dash + dot + dash + dot + lSpace,
	"=":  dash + dot + dot + dot + dash + lSpace,
	"+":  dot + dash + dot + dash + dot + lSpace,
	"-":  dash + dot + dot + dot + dot + dash + lSpace,
	"_":  dot + dot + dash + dash + dot + dash + lSpace,
	"\"": dot + dash + dot + dot + dash + dot + lSpace,
	"$":  dot + dot + dot + dash + dot + dot + dash + lSpace,
	"@":  dot + dash + dash + dot + dash + dot + lSpace,
	" ":  wSpace,
}

var ItuToEMap = map[string]string{
	"*-":      "a",
	"-***":    "b",
	"-*-*":    "c",
	"-**":     "d",
	"*":       "e",
	"**-*":    "f",
	"--*":     "g",
	"****":    "h",
	"**":      "i",
	"*---":    "j",
	"-*-":     "k",
	"*-**":    "l",
	"--":      "m",
	"-*":      "n",
	"---":     "o",
	"*--*":    "p",
	"--*-":    "q",
	"*-*":     "r",
	"***":     "s",
	"-":       "t",
	"**-":     "u",
	"***-":    "v",
	"*--":     "w",
	"-**-":    "x",
	"-*--":    "y",
	"--**":    "z",
	"-----":   "0",
	"*----":   "1",
	"**---":   "2",
	"***--":   "3",
	"****-":   "4",
	"*****":   "5",
	"-****":   "6",
	"--***":   "7",
	"---**":   "8",
	"----*":   "9",
	"*-*-*-":  ".",
	"--**--":  ",",
	"**--**":  "?",
	"*----*":  "'",
	"-*-*--":  "!",
	"-**-*":   "/",
	"-*--*":   "(",
	"-*--*-":  ")",
	"*-***":   "&",
	"---***":  ":",
	"-*-*-*":  ";",
	"-***-":   "=",
	"*-*-*":   "+",
	"-****-":  "-",
	"**--*-":  "_",
	"*-**-*":  "\"",
	"***-**-": "$",
	"*--*-*":  "@",
	lSpace:    "",
}
